- name: install sway
  community.general.pacman:
    name: sway
    state: present
  become: true

- name: install wofi
  community.general.pacman:
    name: wofi
    state: present
  become: true

- name: install waybar
  community.general.pacman:
    name: waybar
    state: present
  become: true

- name: install waybar deps font
  community.general.pacman:
    name: otf-font-awesome
    state: present
  become: true

- name: install swayidle
  community.general.pacman:
    name: swayidle
    state: present
  become: true

- name: install swaylock
  community.general.pacman:
    name: swaylock
    state: present
  become: true

- name: install autotiling
  community.general.pacman:
    name: autotiling
    state: present
  become: true

- name: install alacritty
  community.general.pacman:
    name: alacritty
    state: present
  become: true

- name: make alacritty conf dir
  ansible.builtin.file:
    name: "~/.config/alacritty"
    state: directory
    recurse: true

- name: copy alacritty toml
  ansible.builtin.copy:
    src: "templates/alacritty.toml"
    dest: "~/.config/alacritty/alacritty.toml"

- name: make sway lock config dir
  ansible.builtin.file:
    path: "~/.swaylock/"
    state: directory

- name: copy swaylock config
  ansible.builtin.copy:
    src: "templates/swaylock_cfg"
    dest: "~/.swaylock/config"

- name: copy swaylock image
  ansible.builtin.copy:
    src: "templates/sway/arch_new_locked.png"
    dest: "~/.swaylock/lock_image.png"

- name: make sway config dir
  ansible.builtin.file:
    path: "~/.config/sway/config.d"
    state: directory
    recurse: yes

- name: copy sway config
  ansible.builtin.copy:
    src: "templates/sway/config"
    dest: "~/.config/sway/"

- name: make wofi config dir
  ansible.builtin.file:
    path: "~/.config/wofi"
    state: directory
    recurse: yes

- name: copy wofi config
  ansible.builtin.copy:
    src: "templates/wofi.css"
    dest: "~/.config/wofi/"

- name: copy bg image config
  ansible.builtin.copy:
    src: "templates/sway/arch_new.png"
    dest: "~/.config/sway/"

- name: copy sway volume ctl config
  ansible.builtin.copy:
    src: "templates/sway/config.d/audio_volume_ctl"
    dest: "~/.config/sway/config.d/"

- name: copy window settings config
  ansible.builtin.copy:
    src: "templates/sway/config.d/window_settings"
    dest: "~/.config/sway/config.d/"

- name: copy short_cuts config
  ansible.builtin.copy:
    src: "templates/sway/config.d/short_cuts"
    dest: "~/.config/sway/config.d/"

